### ISSUE TITLE
[BUG] Encoding bitrate is broken (color artifacts)

### ISSUE THREAD

**Issue by tkslan** [Unity-Technologies/com.unity.webrtc#127]
Hi, after switch to 2.0.3 seems like encoding quality is much worse (color artifacts etc.) 
In version 1 (with static 10mbps bitrate value) encoder seems to have much better quality.
Tested on 2019LTS (Windows), with NV encoder.

**Comment by karasusan** [comment]
We are preparing a feature which can change the bitrate value for the next version.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/118

**Comment by WaltzBinaire** [comment]
Hey guys! Thanks for your hard work! Is there any chance this will be fixed any time soon? I can not tell if this is related to this issue from april https://github.com/Unity-Technologies/com.unity.webrtc/issues/100 - but for whatever reason im not able to establish an acceptable quality without huge artifacts since month. On localhost or aws. I believe that beside the many things you guys have on your agenda - a basic demo quality might be more then a feature.

**Comment by karasusan** [comment]
Same issue #100

**Comment by karasusan** [comment]
@WaltzBinaire 
Hi, Have you resolved your issue with the latest version of package?
I want to close this issue if you have no problem.

**Comment by WaltzBinaire** [comment]
yes closed from our side - thank you very much - hope @tkslan also agrees

**Comment by tkslan** [comment]
@WaltzBinaire hope its fixed :)  I have done a backport from V1 (https://github.com/tkslan/com.unity.webrtc/commit/e97b163e521bb952e4ec57022eebe91ff03053bc) and didn't used latest package.
