### ISSUE TITLE
[BUG] Is there any evidence that TURN servers are being used at all or work with the library?

### ISSUE THREAD

**Issue by doctorpangloss** [Unity-Technologies/com.unity.webrtc#504]
**Describe the bug**
RTCConfiguration of the form
```
{ "iceTransportPolicy": "relay", "iceServers": [ { "credential": "....", "urls": [ "turn:10.10.10.10:1111?transport=udp" ], "username": "..." }
```
results in the Unity WebRTC library not connecting to the server, based on the lack of any logs or STUN packets being received from the Unity application.

In contrast, the same configuration is correctly used by Chrome and results in STUN packets being received.

**Expected behavior**
Unity WebRTC should use a TURN server.

You must be just directly networking the entire VM in Furioos.

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Unity Version: 2020.3 LTS
 - Package version: 2.3.3-preview

**This issue reproduces on 2.4.0-exp2 & later**

**Comment by urirvana** [comment]
I'm also facing this issue. 

The Unity implementation of Audio streaming & Data channel isn't able to establish a peer connection (Unity Editor to Unity Editor, neither Unity Editor to Android).

I'm using Coturn (https://github.com/coturn/coturn) in AWS with long term credentials and when forcing relay through:

_iceTransportPolicy = RTCIceTransportPolicy.Relay_

it does not establish a connection (from what I can see in the Turn Server Logs the TCP connection is closed before finalizing the connection).

It works if _iceTransportPolicy_ is not forced to relay (connects using Stun),

Worth mentioning that same configuration works (not using Unity WebRTC) on a web browser to web browser (chrome & edge) and peers can establish a connection fine and use Coturn as relay. 

Not sure if part of the Turn Server Logs will help but here they are anyways.

Notes about logs:
* Sensitive information was renamed
* The 401: Unauthorized does not seem to be related because credentials are sent afterwards and the same messages are printed even in a working run on a web browser.

[Editor-To-Android-Not-Working.txt](https://github.com/Unity-Technologies/com.unity.webrtc/files/6966247/Editor-To-Android-Not-Working.txt)
[Chrome-To-Chrome-Working.txt](https://github.com/Unity-Technologies/com.unity.webrtc/files/6966249/Chrome-To-Chrome-Working.txt)

**Comment by doctorpangloss** [comment]
TURN servers appear to work correctly now in the latest develop branch.

As a side effect many users who were not having any TURN success will suddenly see much longer negotiations.

**Comment by urirvana** [comment]
Still not working in my case with latest branch.

@doctorpangloss did you force webrtc to use relay?

How did you find out it is using relay?

**Comment by doctorpangloss** [comment]
I take it back. TURN relays are not working.

**Comment by doctorpangloss** [comment]
I think TURN relays work. It was just some other bug.

**Comment by urirvana** [comment]
Right, TURN is working, negotiation was the issue on my end. 

Forcing "relay" is working as expected
