### ISSUE TITLE
[REQUEST] Expose incoming video stream within Unity (receiver) 

### ISSUE THREAD

**Issue by ZeoWorks** [Unity-Technologies/com.unity.webrtc#551]
Hi,
It would be great if we can get a byte[] array of the incoming video stream packets.
This would allow us to use the byte[] array data for custom decoder plugins. :)

Do we have an ETA as to when the next version of com.unity.webrtc and com.unity.renderstreaming will be released?

**Comment by karasusan** [comment]
Maybe your request is achieved by Encoded Transform API. We will develop the feature in the future.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/305

The next version of renderstreaming should be released the end of this month. And we will focus on the performance issue of WebRTC package since next month.

**Comment by gtk2k** [comment]
Does that mean that the Encoded Transform equivalent will be implemented and released at the end of this month?

**Comment by karasusan** [comment]
> Does that mean that the Encoded Transform equivalent will be implemented and released at the end of this month?
No. I think we can start to develop for Encoded Transform from February at the earliest.

**Comment by gtk2k** [comment]
got it

**Comment by karasusan** [comment]
memo: WRS-160

**Comment by gtk2k** [comment]
The long-awaited feature is finally here!
